name: weather_app
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # this is used to get the current location of the user
  geocoding: ^2.0.4
  # this is used to get the longitude and latitude of the user
  geolocator: ^9.0.0
  # for flexible dependency injection
  get_it: ^7.2.0
  # this is used to communicate with the API
  http: ^0.13.4
  # this is used to format the date into readable format
  intl: ^0.17.0
  # this is used to override the default setting in the geolocator library
  permission_handler: ^9.2.0
  # this is used for state management (and DI)
  provider: ^6.0.3
  # this is used to work with SVG images
  websafe_svg: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
